### ISSUE TITLE
IO Error - Mac 10.7.5

### ISSUE THREAD

**Issue by kylebjordahl** [fazalmajid/cs1504#2]
So, I'm not the sharpest with Python, here's what I'm getting:

Using device /dev/cu.usbserial... Traceback (most recent call last):
  File "cs1504.py", line 323, in <module>
    scanner.interrogate()
  File "cs1504.py", line 167, in interrogate
    raise IOError
IOError

I don't mind tinkering in the code, but do you have any ideas what might be causing it to timeout? I believe I have the correct drivers installed, and the port is showing up in /dev/.

Using Mac OS X 10.7.5 and Python 2.7.1 (OS default, I think)

**Comment by Gasman2014** [comment]
I have just acquired one of these scanners and was hoping that I could use your script to drive it. Using OS 10.11, Python 2.7 I get exactly the same error as @kylebjordahl. The program loops around       `self.send('\x01\x02\x00')` 50 times and then fails. The /dev/ttyusb entry is showing up when the converter is plugged in and the LED flashes during the connection process. Running as root makes no difference.
I can connect using the CS1504 'Mini Utility' using VirtualBox and Windows which leads me to believe that all the hardware and serial to USB converter is OK. I have tried adding  `self.ser.setDTR(1)` to the end of the def__init__ section (as a previous user suggested) but no luck.
Any advice? I appreciate that this device and this thread are now quite old but I know that these scanners are still being used.

**Comment by Gasman2014** [comment]
Please ignore above - I have now identified that this is a driver issue. After updating the Prolific Driver to the version from www.mac-usb-serial.com whic seems to have solved the issue. Get what you pay for - FTDI chips never caused me this grief!

**Comment by wheelerj** [comment]
I'm glad you figured it out. We eventually abandoned these scanners in 
favor of CS3000's.

**Comment by Gasman2014** [comment]
I hope the driver update might improve the connection to a couple of cheap arduino clones too. I needed a cheap barcode scanner and picked up the 1504 for £4 so a bit of a bargain and your software clinched the deal!

John Pateman

**Comment by fazalmajid** [comment]
Glad you found it useful. I haven't used it in a long time, as I myself switched to Delicious Library with its RoV Bluetooth scanner.
